version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=mysql
      - DB_USER=mohammed
      - DB_PASSWORD=password
      - DB_NAME=JSSmartExam
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: JSSmartExam
      MYSQL_USER: mohammed
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"  # Change to a different host port if necessary
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
